---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-component-sbom
  labels:
    app.kubernetes.io/version: "0.2.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Update component-level SBOM with purls with release-time info.
  params:
    - name: sbomJsonPath
      description: Relative path to the SBOM data file in the workspace.
      type: string
    - name: downloadedSbomPath
      description: |
        Path to the directory holding previously downloaded SBOMs to be updated.
      type: string
  workspaces:
    - name: data
      description: The workspace where the SBOM files reside.
  steps:
    - name: update-component-sbom-purls
      image: quay.io/konflux-ci/release-service-utils:4a67d0c959e63cbb4bc0d37db1ce962091d6072a
      script: |
        #!/usr/bin/env bash
        set -eux

        INPUT_PATH="$(workspaces.data.path)/$(params.downloadedSbomPath)"

        #update the SBOM files in place
        update_component_sbom \
          --data-path "$(workspaces.data.path)/$(params.sbomJsonPath)" \
          --input-path "$INPUT_PATH" \
          --output-path "$INPUT_PATH"
