---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-product-sbom
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Create product-level SBOM from release notes.
  params:
    - name: dataJsonPath
      description: Relative path to the JSON data file in the workspace.
      type: string
  workspaces:
    - name: data
      description: Workspace to save the product-level SBOM to.
  results:
    - name: productSBOMPath
      description: Relative path to the created product-level SBOM in the data workspace.
  steps:
    - name: create-sbom
      image: quay.io/konflux-ci/release-service-utils:31c0a95a9604fd16b002b4969cfd74753d9c5e77
      script: |
        #!/usr/bin/env bash
        set -eux

        SBOM_FILE="product_sbom.json"
        SBOM_PATH="$(dirname "$(params.dataJsonPath)")/${SBOM_FILE}"
        OUTPUT_PATH=$(workspaces.data.path)/${SBOM_PATH}

        create_product_sbom --data-path "$(workspaces.data.path)/$(params.dataJsonPath)" \
          --output-path "$OUTPUT_PATH"

        echo -n "$SBOM_PATH" > "$(results.productSBOMPath.path)"
