---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: update-internal-services-manager
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "release, tenant"
spec:
  description: >-
    Tekton pipeline to update the internal-services manager yaml to the latest image in the
    hacbs-release/app-interface-deployments repository.
  params:
    - name: release
      type: string
      description:
        The namespaced name (namespace/name) of the Release custom resource initiating this pipeline execution
    - name: repoUrl
      type: string
      description: The repository where the internal-services manager files to update are
    - name: githubSecret
      type: string
      description: The secret containing a TOKEN key to authenticate with GitHub to the repoUrl
  tasks:
    - name: get-git-sha-image-ref-from-release
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/konflux-ci/release-service-catalog.git
          - name: revision
            value: development
          - name: pathInRepo
            value: tasks/tenant/get-git-sha-image-ref-from-release/get-git-sha-image-ref-from-release.yaml
      params:
        - name: release
          value: $(params.release)
    - name: update-staging-manager
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/konflux-ci/release-service-catalog.git
          - name: revision
            value: development
          - name: pathInRepo
            value: tasks/tenant/update-manager-image-in-git/update-manager-image-in-git.yaml
      params:
        - name: mode
          value: push
        - name: repoBranch
          value: main
        - name: repoUrl
          value: $(params.repoUrl)
        - name: githubSecret
          value: $(params.githubSecret)
        - name: image
          value: $(tasks.get-git-sha-image-ref-from-release.results.imageRef)
    - name: update-production-manager
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/konflux-ci/release-service-catalog.git
          - name: revision
            value: development
          - name: pathInRepo
            value: tasks/tenant/update-manager-image-in-git/update-manager-image-in-git.yaml
      params:
        - name: mode
          value: pr
        - name: repoBranch
          value: stable
        - name: repoUrl
          value: $(params.repoUrl)
        - name: githubSecret
          value: $(params.githubSecret)
        - name: image
          value: $(tasks.get-git-sha-image-ref-from-release.results.imageRef)
