---
name: Update Internal Branch

on:
  push:
    branches: [development]
    
permissions: 
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "konflux-release-team@redhat.com"

      - name: Update Internal Branch
        run: |
          git checkout -b internal
          git push -f origin internal
